### ISSUE TITLE
New variable/parameter does not work anymore

### ISSUE THREAD

**Issue by dannoe** [wbrakowski/AL-Navigator#112]
Reproducing steps:

- I am trying to use a variable ``Test`` that does not yet exist.
- I select the code action / quick fix "Add local variable Test".
- Nothing happens.

In the "Extension Host" output I get the following 

```
2023-10-11 09:18:36.472 [error] TypeError: name.trim is not a function
    at Object.fromNameText (c:\Users\<user>\.vscode\extensions\wbrakowski.al-navigator-0.5.4\out\additional\stringFunctions.js:23:21)
    at Function.<anonymous> (c:\Users\<user>\.vscode\extensions\wbrakowski.al-navigator-0.5.4\out\al_code_outline\devToolsExtensionContext.js:130:76)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\<user>\.vscode\extensions\wbrakowski.al-navigator-0.5.4\out\al_code_outline\devToolsExtensionContext.js:6:58)
```

**Comment by wbrakowski** [comment]
@dannoe @nickgoddard777 
Hey. Sorry for the late response and thank you for reporting this issue.
I will try to fix this as soon as possible.

**Comment by wbrakowski** [comment]
@dannoe Thank you for your pull request. I just saw it and merged it. You should be able to use the extension in a few minutes when it is successfully published to the market place.
