### ISSUE TITLE
Add local/global variable throws an error

### ISSUE THREAD

**Issue by dannoe** [wbrakowski/AL-Navigator#118]
```
2024-01-17 08:43:38.766 [error] TypeError: azALDevTools.alLangProxy.getCompletionForSourceCode is not a function
    at Function.<anonymous> (c:\Users\user\.vscode\extensions\wbrakowski.al-navigator-0.5.6\out\al_code_outline\devToolsExtensionContext.js:103:55)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\user\.vscode\extensions\wbrakowski.al-navigator-0.5.6\out\al_code_outline\devToolsExtensionContext.js:6:58)
```
``getCompletionForSourceCode`` does not exist anymore and was marked obsolete 2 years ago (see https://github.com/anzwdev/al-code-outline/blob/8285783c916b3eecf369be1c4fd58c12dda51bb1/vscode-extension/src/allanguage/alLangServerProxy.ts#L153)

**Comment by wbrakowski** [comment]
@dannoe Thank you for reporting, I will check this.
